[staging]
source = "/home/ricky/dotfiles/"
description = "This is the staging profile, used for testing new configurations before they are moved to the main profile."

[new_profile]
source = "/home/ricky/other_dotfiles/"
description = "This is a new profile for testing purposes. It can be used to manage a different set of dotfiles without affecting the main or staging profiles."

[main]
source = "/home/ricky/main_dotfiles/"
description = "This is the main profile, containing the stable and regularly used configurations. Changes to this profile should be made with caution, as it is the primary source for the user's dotfiles."
